"""add_file_retention_and_cleanup

Revision ID: 7cd2ada1224c
Revises: a274234b7a09
Create Date: 2025-10-31 16:45:23.408779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd2ada1224c'
down_revision = 'a274234b7a09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('retention_days', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'expires_at')
    op.drop_column('files', 'retention_days')
    # ### end Alembic commands ###

