"""add_comment_confirmations

Revision ID: 59e10a995358
Revises: 7cd2ada1224c
Create Date: 2025-10-31 16:49:54.151438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e10a995358'
down_revision = '7cd2ada1224c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_comments', sa.Column('status', sa.String(), nullable=True))
    op.add_column('card_comments', sa.Column('status_reason', sa.Text(), nullable=True))
    op.add_column('card_comments', sa.Column('status_by_id', sa.Integer(), nullable=True))
    op.add_column('card_comments', sa.Column('status_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'card_comments', 'users', ['status_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card_comments', type_='foreignkey')
    op.drop_column('card_comments', 'status_at')
    op.drop_column('card_comments', 'status_by_id')
    op.drop_column('card_comments', 'status_reason')
    op.drop_column('card_comments', 'status')
    # ### end Alembic commands ###

