"""add_calendar_event_shared_users

Revision ID: 3656f8fa9c14
Revises: b2a88a4faa0d
Create Date: 2025-10-31 18:42:19.212363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3656f8fa9c14'
down_revision = 'b2a88a4faa0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_event_shared_users',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_event_shared_users')
    # ### end Alembic commands ###

